version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: emg-analyzer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --timeout 300
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - emg-network

  # Redis Insight (optional - Redis GUI)
  redis-insight:
    image: redis/redisinsight:latest
    container_name: emg-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - emg-network

volumes:
  redis_data:
    driver: local

networks:
  emg-network:
    driver: bridge

# Usage:
# docker-compose -f docker-compose.redis.yml up -d
# 
# Environment variables for backend:
# REDIS_URL=redis://localhost:6379/0
# REDIS_CACHE_TTL_SECONDS=3600
# REDIS_MAX_CACHE_SIZE_MB=100