-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bfr_monitoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  channel_name text NOT NULL CHECK (channel_name = ANY (ARRAY['CH1'::text, 'CH2'::text])),
  target_pressure_aop double precision CHECK (target_pressure_aop >= 0::double precision AND target_pressure_aop <= 100::double precision),
  actual_pressure_aop double precision CHECK (actual_pressure_aop >= 0::double precision AND actual_pressure_aop <= 100::double precision),
  cuff_pressure_mmhg double precision CHECK (cuff_pressure_mmhg >= 0::double precision),
  systolic_bp_mmhg double precision CHECK (systolic_bp_mmhg >= 80::double precision AND systolic_bp_mmhg <= 250::double precision),
  diastolic_bp_mmhg double precision CHECK (diastolic_bp_mmhg >= 40::double precision AND diastolic_bp_mmhg <= 150::double precision),
  bfr_compliance_manual boolean,
  safety_compliant boolean NOT NULL DEFAULT true,
  measurement_timestamp timestamp with time zone DEFAULT now(),
  measurement_method text DEFAULT 'manual'::text CHECK (measurement_method = ANY (ARRAY['sensor'::text, 'manual'::text, 'estimated'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bfr_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT bfr_monitoring_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.therapy_sessions(id)
);
CREATE TABLE public.emg_statistics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  channel_name text NOT NULL,
  total_contractions integer DEFAULT 0 CHECK (total_contractions >= 0),
  good_contractions integer DEFAULT 0 CHECK (good_contractions >= 0),
  mvc_contraction_count integer DEFAULT 0 CHECK (mvc_contraction_count >= 0),
  duration_contraction_count integer DEFAULT 0 CHECK (duration_contraction_count >= 0),
  compliance_rate double precision DEFAULT 0.0 CHECK (compliance_rate >= 0.0::double precision AND compliance_rate <= 1.0::double precision),
  mvc_value double precision CHECK (mvc_value > 0::double precision),
  mvc_threshold double precision CHECK (mvc_threshold > 0::double precision),
  mvc_threshold_actual_value double precision,
  duration_threshold_actual_value double precision,
  total_time_under_tension_ms double precision CHECK (total_time_under_tension_ms >= 0::double precision),
  avg_duration_ms double precision CHECK (avg_duration_ms >= 0::double precision),
  max_duration_ms double precision CHECK (max_duration_ms >= 0::double precision),
  min_duration_ms double precision CHECK (min_duration_ms >= 0::double precision),
  avg_amplitude double precision CHECK (avg_amplitude >= 0::double precision),
  max_amplitude double precision CHECK (max_amplitude >= 0::double precision),
  rms_mean double precision CHECK (rms_mean >= 0::double precision),
  rms_std double precision CHECK (rms_std >= 0::double precision),
  mav_mean double precision CHECK (mav_mean >= 0::double precision),
  mav_std double precision CHECK (mav_std >= 0::double precision),
  mpf_mean double precision CHECK (mpf_mean >= 0::double precision),
  mpf_std double precision CHECK (mpf_std >= 0::double precision),
  mdf_mean double precision CHECK (mdf_mean >= 0::double precision),
  mdf_std double precision CHECK (mdf_std >= 0::double precision),
  fatigue_index_mean double precision,
  fatigue_index_std double precision CHECK (fatigue_index_std >= 0::double precision),
  fatigue_index_fi_nsm5 double precision,
  signal_quality_score double precision CHECK (signal_quality_score >= 0.0::double precision AND signal_quality_score <= 1.0::double precision),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT emg_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT emg_statistics_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.therapy_sessions(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  therapist_id uuid NOT NULL,
  patient_code text NOT NULL DEFAULT ('P'::text || lpad((nextval('patient_code_seq'::regclass))::text, 3, '0'::text)) UNIQUE,
  age_group text CHECK (age_group = ANY (ARRAY['18-30'::text, '31-50'::text, '51-70'::text, '71+'::text])),
  gender text CHECK (gender = ANY (ARRAY['M'::text, 'F'::text, 'NB'::text, 'NS'::text])),
  pathology_category text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT true,
  current_mvc_ch1 double precision CHECK (current_mvc_ch1 > 0::double precision),
  current_mvc_ch2 double precision CHECK (current_mvc_ch2 > 0::double precision),
  current_duration_ch1 double precision CHECK (current_duration_ch1 > 0::double precision),
  current_duration_ch2 double precision CHECK (current_duration_ch2 > 0::double precision),
  last_assessment_date timestamp with time zone,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.performance_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  overall_score double precision DEFAULT 0.0 CHECK (overall_score >= 0.0::double precision AND overall_score <= 100.0::double precision),
  compliance_score double precision DEFAULT 0.0 CHECK (compliance_score >= 0.0::double precision AND compliance_score <= 100.0::double precision),
  symmetry_score double precision CHECK (symmetry_score >= 0.0::double precision AND symmetry_score <= 100.0::double precision),
  effort_score double precision CHECK (effort_score >= 0.0::double precision AND effort_score <= 100.0::double precision),
  game_score double precision CHECK (game_score >= 0.0::double precision AND game_score <= 100.0::double precision),
  left_muscle_compliance double precision CHECK (left_muscle_compliance >= 0.0::double precision AND left_muscle_compliance <= 100.0::double precision),
  right_muscle_compliance double precision CHECK (right_muscle_compliance >= 0.0::double precision AND right_muscle_compliance <= 100.0::double precision),
  completion_rate_left double precision CHECK (completion_rate_left >= 0.0::double precision AND completion_rate_left <= 1.0::double precision),
  completion_rate_right double precision CHECK (completion_rate_right >= 0.0::double precision AND completion_rate_right <= 1.0::double precision),
  intensity_rate_left double precision CHECK (intensity_rate_left >= 0.0::double precision AND intensity_rate_left <= 1.0::double precision),
  intensity_rate_right double precision CHECK (intensity_rate_right >= 0.0::double precision AND intensity_rate_right <= 1.0::double precision),
  duration_rate_left double precision CHECK (duration_rate_left >= 0.0::double precision AND duration_rate_left <= 1.0::double precision),
  duration_rate_right double precision CHECK (duration_rate_right >= 0.0::double precision AND duration_rate_right <= 1.0::double precision),
  bfr_compliant boolean NOT NULL DEFAULT true,
  bfr_pressure_aop double precision CHECK (bfr_pressure_aop >= 0.0::double precision AND bfr_pressure_aop <= 100.0::double precision),
  rpe_post_session integer CHECK (rpe_post_session >= 0 AND rpe_post_session <= 10),
  game_points_achieved integer CHECK (game_points_achieved >= 0),
  game_points_max integer CHECK (game_points_max >= 0),
  created_at timestamp with time zone DEFAULT now(),
  scoring_config_id uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_scores_pkey PRIMARY KEY (id),
  CONSTRAINT performance_scores_scoring_config_id_fkey FOREIGN KEY (scoring_config_id) REFERENCES public.scoring_configuration(id),
  CONSTRAINT performance_scores_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.therapy_sessions(id)
);
CREATE TABLE public.processing_parameters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  sampling_rate_hz double precision NOT NULL CHECK (sampling_rate_hz > 0::double precision),
  filter_low_cutoff_hz double precision NOT NULL DEFAULT 20.0,
  filter_high_cutoff_hz double precision NOT NULL DEFAULT 500.0,
  filter_order integer NOT NULL DEFAULT 4 CHECK (filter_order > 0 AND filter_order <= 8),
  rms_window_ms double precision NOT NULL DEFAULT 50.0 CHECK (rms_window_ms > 0::double precision AND rms_window_ms <= 1000::double precision),
  rms_overlap_percent double precision NOT NULL DEFAULT 50.0 CHECK (rms_overlap_percent >= 0::double precision AND rms_overlap_percent < 100::double precision),
  mvc_window_seconds double precision NOT NULL DEFAULT 3.0 CHECK (mvc_window_seconds > 0::double precision AND mvc_window_seconds <= 30::double precision),
  mvc_threshold_percentage double precision NOT NULL DEFAULT 75.0 CHECK (mvc_threshold_percentage > 0::double precision AND mvc_threshold_percentage <= 100::double precision),
  processing_version text NOT NULL DEFAULT '1.0'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  mvc_source character varying DEFAULT 'self_calibration'::character varying,
  algorithm_config jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT processing_parameters_pkey PRIMARY KEY (id),
  CONSTRAINT processing_parameters_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.therapy_sessions(id)
);
CREATE TABLE public.scoring_configuration (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  configuration_name text NOT NULL,
  description text,
  weight_compliance numeric NOT NULL DEFAULT 0.400,
  weight_symmetry numeric NOT NULL DEFAULT 0.250,
  weight_effort numeric NOT NULL DEFAULT 0.200,
  weight_game numeric NOT NULL DEFAULT 0.150,
  weight_completion numeric NOT NULL DEFAULT 0.333,
  weight_intensity numeric NOT NULL DEFAULT 0.333,
  weight_duration numeric NOT NULL DEFAULT 0.334,
  active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  therapist_id uuid,
  is_global boolean NOT NULL DEFAULT false,
  CONSTRAINT scoring_configuration_pkey PRIMARY KEY (id),
  CONSTRAINT scoring_configuration_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.session_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  mvc_threshold_percentage double precision NOT NULL DEFAULT 75.0 CHECK (mvc_threshold_percentage > 0::double precision AND mvc_threshold_percentage <= 100::double precision),
  target_contractions integer NOT NULL DEFAULT 12 CHECK (target_contractions > 0),
  expected_contractions_per_muscle integer DEFAULT 12 CHECK (expected_contractions_per_muscle > 0),
  bfr_enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  target_mvc_ch1 double precision CHECK (target_mvc_ch1 > 0::double precision),
  target_mvc_ch2 double precision CHECK (target_mvc_ch2 > 0::double precision),
  target_duration_ch1 double precision CHECK (target_duration_ch1 > 0::double precision),
  target_duration_ch2 double precision CHECK (target_duration_ch2 > 0::double precision),
  target_contractions_ch1 integer DEFAULT 12,
  target_contractions_ch2 integer DEFAULT 12,
  therapist_id uuid,
  duration_threshold_seconds double precision NOT NULL DEFAULT 2.0 CHECK (duration_threshold_seconds > 0::double precision),
  CONSTRAINT session_settings_pkey PRIMARY KEY (id),
  CONSTRAINT session_settings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.therapy_sessions(id)
);
CREATE TABLE public.therapy_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_path text NOT NULL UNIQUE,
  file_hash text NOT NULL UNIQUE,
  file_size_bytes bigint NOT NULL CHECK (file_size_bytes > 0),
  patient_id uuid,
  therapist_id uuid,
  session_id text,
  session_date timestamp with time zone,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'reprocessing'::text])),
  processing_error_message text,
  processing_time_ms double precision CHECK (processing_time_ms >= 0::double precision),
  game_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT therapy_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT therapy_sessions_therapist_id_fkey FOREIGN KEY (therapist_id) REFERENCES public.user_profiles(id),
  CONSTRAINT therapy_sessions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['therapist'::text, 'researcher'::text, 'admin'::text])),
  first_name text,
  last_name text,
  full_name text DEFAULT 
CASE
    WHEN ((first_name IS NOT NULL) AND (last_name IS NOT NULL)) THEN ((first_name || ' '::text) || last_name)
    WHEN (full_name_override IS NOT NULL) THEN full_name_override
    ELSE 'Unknown User'::text
END,
  full_name_override text,
  institution text,
  department text,
  access_level text DEFAULT 'basic'::text CHECK (access_level = ANY (ARRAY['full'::text, 'advanced'::text, 'basic'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login timestamp with time zone,
  active boolean DEFAULT true,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);